import { sql } from 'drizzle-orm';
import { pgTable, uuid, text, timestamp, boolean, jsonb, integer, unique, index } from 'drizzle-orm/pg-core';
import { tenants } from './tenants';
import { session } from './users';
const created = () => timestamp('created_at', {withTimezone:true}).notNull().defaultNow();
export const pulseSites=pgTable('pulse_sites',{
 id:uuid('id').primaryKey().defaultRandom(),tenantId:uuid('tenant_id').notNull().references(()=>tenants.id,{onDelete:'cascade'}),publicId:text('public_id').notNull().unique(),name:text('name').notNull(),platform:text('platform').notNull(),integrationKey:text('integration_key'),collection:text('collection').notNull(),environment:text('environment').notNull(),allowedOrigins:jsonb('allowed_origins').notNull().default([]),timezone:text('timezone').notNull().default('UTC'),identityMode:text('identity_mode').notNull().default('ephemeral'),enabled:boolean('enabled').notNull().default(true),createdAt:created()
},t=>[unique().on(t.tenantId,t.name,t.environment),index('pulse_sites_tenant_idx').on(t.tenantId)]);
export const pulseServerCredentials=pgTable('pulse_server_credentials',{id:uuid('id').primaryKey().defaultRandom(),siteId:uuid('site_id').notNull().references(()=>pulseSites.id,{onDelete:'cascade'}),secretHash:text('secret_hash').notNull().unique(),revokedAt:timestamp('revoked_at',{withTimezone:true}),createdAt:created()});
export const pulseGoals=pgTable('pulse_goals',{id:uuid('id').primaryKey().defaultRandom(),siteId:uuid('site_id').notNull().references(()=>pulseSites.id,{onDelete:'cascade'}),eventName:text('event_name').notNull(),createdAt:created()},t=>[unique().on(t.siteId,t.eventName)]);
export const pulseFunnels=pgTable('pulse_funnels',{id:uuid('id').primaryKey().defaultRandom(),siteId:uuid('site_id').notNull().references(()=>pulseSites.id,{onDelete:'cascade'}),name:text('name').notNull(),steps:jsonb('steps').notNull(),windowMs:integer('window_ms').notNull().default(1800000),createdAt:created()});
export const pulseVerifications=pgTable('pulse_verifications',{tokenHash:text('token_hash').primaryKey(),siteId:uuid('site_id').notNull().references(()=>pulseSites.id,{onDelete:'cascade'}),environment:text('environment').notNull(),issuedAt:timestamp('issued_at',{withTimezone:true}).notNull().defaultNow(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull().default(sql`now()+interval '10 minutes'`)},t=>[index('pulse_verifications_site_idx').on(t.siteId,t.expiresAt)]);
export const pulseSessionHandoffs=pgTable('pulse_session_handoffs',{codeHash:text('code_hash').primaryKey(),stateHash:text('state_hash').notNull(),sessionId:text('session_id').notNull().references(()=>session.id,{onDelete:'cascade'}),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull().default(sql`now()+interval '60 seconds'`)});
export const pulseActivity=pgTable('pulse_activity',{id:uuid('id').primaryKey().defaultRandom(),tenantId:uuid('tenant_id').notNull().references(()=>tenants.id,{onDelete:'cascade'}),siteId:uuid('site_id').references(()=>pulseSites.id,{onDelete:'set null'}),kind:text('kind').notNull(),metadata:jsonb('metadata').notNull().default({}),createdAt:created()},t=>[index('pulse_activity_tenant_idx').on(t.tenantId,t.createdAt)]);
export const pulseBusinessOutbox=pgTable('pulse_business_outbox',{id:uuid('id').primaryKey().defaultRandom(),siteId:uuid('site_id').notNull().references(()=>pulseSites.id,{onDelete:'cascade'}),tenantId:uuid('tenant_id').notNull(),environment:text('environment').notNull(),eventId:text('event_id').notNull(),eventName:text('event_name').notNull(),occurredAt:timestamp('occurred_at',{withTimezone:true}).notNull().defaultNow(),properties:jsonb('properties').notNull().default({}),createdAt:created()},t=>[unique().on(t.siteId,t.eventId),index('pulse_business_outbox_pending_idx').on(t.createdAt)]);
